exman3/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r"", include("expenses.urls")),
    url(r"^login/$", login, kwargs={
        'template_name': 'form.html',
    }, name="login"),
    url(r"^logout/$", logout_then_login, name="logout"),
    url(r'^admin/', admin.site.urls),
]

expenses/urls.py
from django.conf.urls import url

from . import views

app_name = "expenses"
urlpatterns = [
    url(r'^$', views.ExpenseListView.as_view(), name="list"),
    url(r'^(?P<pk>[0-9]+)/$', views.ExpenseDetailView.as_view(),
        name="detail"),
    url(r'^create/', views.ExpenseCreateView.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.ExpenseUpdateView.as_view(),
        name="update"),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.ExpenseDeleteView.as_view(),
        name="delete"),

    url(r'^contact/', views.contact_us_view, name='contact'),

    url(r'^my/(\d+)/', views.MyView.as_view(), name='my'),

    # url(r'^login/', views.login_view, name='login'),
    # url(r'^logout/', views.logout_view, name='logout'),

]

expenses/models.py
import decimal

import markdown
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models


class Tag(models.Model):
    name = models.CharField(_("name"), max_length=100, unique=True)

    class Meta:
        verbose_name = _("tag")
        verbose_name_plural = _("tags")

    def __str__(self):
        return self.name


class Expense(models.Model):
    user = models.ForeignKey(User, related_name='expenses',
                             verbose_name=_("user"))
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    title = models.CharField(_("title"), max_length=300)
    amount = models.DecimalField(_("amount"), max_digits=10, decimal_places=2)
    description = models.TextField(_("description"), null=True, blank=True)

    tags = models.ManyToManyField(Tag, blank=True,
                                  related_name='expenses',
                                  # through='ExpenseTag',
                                  )

    class Meta:
        verbose_name = _("expense")
        verbose_name_plural = _("expenses")

    def __str__(self):
        return "[#{}] {} (${})".format(
            self.id,
            self.title,
            self.amount,
        )

    def get_absolute_url(self):
        return reverse("expenses:detail", args=(self.pk,))

    def amount_with_tax(self):
        return self.amount * decimal.Decimal("1.17")

    def latest_comments(self):
        return self.comments.order_by('-created_at')


class Comment(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    expense = models.ForeignKey(Expense, related_name="comments")
    body_markdown = models.TextField(_("comment"))
    body_html = models.TextField(editable=False)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.body_html = markdown.markdown(self.body_markdown)
        super().save(force_insert, force_update, using, update_fields)

# class ExpenseTag(models.Model):
#     created_at = models.DateTimeField(auto_now_add=True)
#     expense = models.ForeignKey(Expense)
#     tag = models.ForeignKey(Tag)
#
#     class Meta:
#         unique_together = (
#             ('expense', 'tag'),
#         )

expenses/forms.py
from django import forms

from expenses.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'body_markdown',
        )

expenses/views.py
import random

from django import forms
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import mail_admins
from django.core.urlresolvers import reverse, reverse_lazy
from django.http.response import HttpResponseBadRequest
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.utils.translation import gettext
from django.views.generic import CreateView, DeleteView, DetailView, ListView, \
    TemplateView, UpdateView

from expenses.forms import CommentForm
from . import models


class ContactUsForm(forms.Form):
    email = forms.EmailField()
    subject = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)
    # date = forms.DateField()


def contact_us_view(request):
    if request.method == "POST":
        form = ContactUsForm(request.POST)

        if form.is_valid():
            mail_admins(form.cleaned_data['subject'],
                        form.cleaned_data['message'])

            messages.success(request, "Your message was sent. Thank you!")

            return redirect(reverse("expenses:list"))

    else:
        form = ContactUsForm()

    return render(request, "form.html", {
        'form': form,
    })


class RequireLoginMixin:
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ExpenseViewMixin(RequireLoginMixin):
    model = models.Expense
    fields = (
        'amount',
        'title',
        'tags',
        'description',
    )

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class ExpenseListView(ExpenseViewMixin, ListView):
    ordering = "-created_at"
    paginate_by = 10


class ExpenseDetailView(ExpenseViewMixin, DetailView):
    def comment_form(self):
        return CommentForm()

    def post(self, request, pk):
        self.object = self.get_object()
        form = CommentForm(request.POST)
        if not form.is_valid():
            if not request.is_ajax():
                return redirect(self.object)
            return HttpResponseBadRequest("bad form")
        form.instance.expense = self.object
        comment = form.save()
        if not request.is_ajax():
            return redirect(self.object)
        return render(request, "expenses/_comment.html", {
            'comment': comment,
        })


class ExpenseCreateView(ExpenseViewMixin, CreateView):
    def form_valid(self, form):
        form.instance.user = self.request.user
        resp = super().form_valid(form)
        messages.success(self.request, gettext("Expense #{} added.").format(
            form.instance.id
        ))
        return resp


class ExpenseUpdateView(ExpenseViewMixin, UpdateView):
    def form_valid(self, form):
        resp = super().form_valid(form)
        messages.success(self.request, "Expense #{} updated.".format(
            form.instance.id
        ))
        return resp


class ExpenseDeleteView(ExpenseViewMixin, DeleteView):
    success_url = reverse_lazy("expenses:list")

    def delete(self, request, *args, **kwargs):
        id = self.get_object().id
        resp = super().delete(request, *args, **kwargs)
        messages.success(self.request, gettext("Expense #{} deleted.").format(
            id
        ))
        return resp


# class MyView(View):
#     def get(self, request, x):
#         return render(request, "my.html")
#     def post(self, request, x):
#         return render(request, "my.html")

class MyView(TemplateView):
    template_name = "my.html"

    bar = 456

    def baz(self):
        return random.randint(1, 10)

        # def get_context_data(self, **kwargs):
        #     d = super().get_context_data(**kwargs)
        #     d['foo'] = 123
        #     d['faz'] = random.randint(1, 10)
        #     return d




        # def get(self, request, x):
        #     return render(request, "my.html", )

        # def post(self, request):
        #     return HttpResponse("xxx")

expenses/templates/_navbar.html
{% load i18n %}

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url "expenses:list" %}">
                {% trans "ExMan3" %}
            </a>
        </div>

        <div class="collapse navbar-collapse"
             id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav pull-right">
                {% if user.is_authenticated %}
                    <li><p class="navbar-text">{{ user }}</p></li>
                    <li><a href="{% url "logout" %}">{% trans "Logout" %}</a></li>
                {% else %}
                    <li><a href="{% url "login" %}">{% trans "Login" %}</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="{% url "expenses:create" %}">{% trans "Create" %}</a></li>
            </ul>
        </div>
    </div>


</nav>

expenses/templates/base.html
{% load bootstrap3 staticfiles i18n %}
{% get_current_language_bidi as bidi %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>


    {% if bidi %}
        <link rel="stylesheet"
              href="{% static "bootstrap/css/bootstrap-rtl.css" %}"/>
    {% else %}
        <link rel="stylesheet"
              href="{% static "bootstrap/css/bootstrap.css" %}"/>

    {% endif %}
    <link rel="stylesheet" href="{% static "main.css" %}"/>

    <title>
        {% block title %}

        {% endblock %}
        | ExMan3

    </title>

</head>
<body {% if bidi %}dir="rtl"{% endif %}>

<div class="container">

    {% include "_navbar.html" %}

    {% bootstrap_messages %}

    {% block content %}
        ***CONTENT***
    {% endblock %}

</div>

<script src="{% static "jquery-3.1.0.js" %}"></script>
<script src="{% static "bootstrap/js/bootstrap.js" %}"></script>
<script src="{% static "csrf.js" %}"></script>

{% block scripts %}
{% endblock %}

</body>
</html>

expenses/templates/contact_us_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}
    {{ object.title }}
{% endblock %}



{% block content %}

    <h1>
        {{ title }}
    </h1>

    <form method="post" novalidate="1">
        {% csrf_token %}

        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "star" %} Submit
            </button>
        {% endbuttons %}
    </form>
{% endblock %}

expenses/templates/expense_list.html
{% extends "base.html" %}

{% block title %}
    Expense List
{% endblock %}

{% block content %}

    <h1>
    ExMan3
    </h1>

    <ul class="list-group">

        {% for object in object_list %}
            <li class="list-group-item">
                <b>
                    <a href="{% url "expenses:detail" object.id %}">{{ object.title }}</a>
                </b>
                ${{ object.amount }}
            </li>
        {% endfor %}

    </ul>

{% endblock %}

expenses/templates/expenses/_comment.html
<li class="list-group-item">
    {{ comment.created_at }}
    {{ comment.body_html|safe }}
</li>

expenses/templates/expenses/expense_confirm_delete.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}
    Delete {{ object.title }}
{% endblock %}

{% block content %}
    <h1>
        Delete {{ object.title }}?
    </h1>
    <form method="post">
        {% csrf_token %}
        <div class="panel panel-default">
            <div class="panel-body">
                {{ object.description|linebreaks }}
            </div>

        </div>

        {% buttons %}
            <button type="submit" class="btn btn-danger">
                {% bootstrap_icon "trash" %} Confirm Delete
            </button>
        {% endbuttons %}

    </form>
{% endblock %}

expenses/templates/expenses/expense_detail.html
{% extends "base.html" %}
{% load i18n bootstrap3 staticfiles %}

{% block title %}
    {{ object.title }}
{% endblock %}

{% block content %}

    <h1><a href="{% url "expenses:list" %}">{% trans "Expenses" %}</a>
        &gt; {{ object.title }} ${{ object.amount }}</h1>

    {{ object.amount_with_tax }}
    <div>
        {{ object.description|linebreaks }}
    </div>
    {% for tag in object.tags.all %}
        <div class="badge badge-default">
            {{ tag }}
        </div>
    {% endfor %}

    <a class="btn btn-primary" href="{% url "expenses:update" object.id %}">
        <i class="glyphicon glyphicon-pencil"></i>
        Edit
    </a>
    <a class="btn btn-danger" href="{% url "expenses:delete" object.id %}">
        <i class="glyphicon glyphicon-trash"></i>
        Delete
    </a>

    <hr>

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form view.comment_form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "save" %} {% blocktrans %}Add
                Comment{% endblocktrans %}
            </button>
        {% endbuttons %}

    </form>

    <ul class="list-group" id="comments">
        {% for comment in object.latest_comments %}
            {% include "expenses/_comment.html" %}
        {% endfor %}
    </ul>


{% endblock %}

{% block scripts %}
    <script src="{% static "expenses/expense_detail.js" %}"></script>
{% endblock %}

expenses/templates/expenses/expense_form.html
{% extends "form.html" %}

{% block title %}
    {% if form.instance.id %}
        Edit {{ object.title }}
    {% else %}
        Add a new expense
    {% endif %}
{% endblock %}

expenses/templates/expenses/expense_list.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}
    Expense List
{% endblock %}

{% block content %}

    <h1>
    ExMan3
    </h1>

    <ul class="list-group">

        {% for object in object_list %}
            <li class="list-group-item">
                <b>
                    <a href="{% url "expenses:detail" object.id %}">{{ object.title }}</a>
                </b>
                ${{ object.amount }}
            </li>
        {% endfor %}

    </ul>

    {% bootstrap_pagination page_obj %}

{% endblock %}

expenses/templates/form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

    <h1>
        {{ title }}
    </h1>

    <form method="post" novalidate="1">
        {% csrf_token %}

        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "star" %} Submit
            </button>
        {% endbuttons %}
    </form>
{% endblock %}

expenses/templates/my.html
hello hello


{{ foo }}

{{ view.bar }}

{{ view.baz }}